---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: todb.testlab.invalid
    image: geerlingguy/docker-centos7-ansible:latest
    command: "/usr/sbin/init"
    privileged: True
    groups:
      - docker_hosts
      - traffic_opsdb
      - traffic_opsdb-primary
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: to.testlab.invalid
    image: geerlingguy/docker-centos7-ansible:latest
    command: "/usr/sbin/init"
    privileged: True
    groups:
      - docker_hosts
      - traffic_ops
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  log: True
  options:
    vvv: True
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      docker-hosts:
        docker_storage_driver: vfs
    host_vars:
      todb.testlab.invalid:
        cdn: ALL
        component: traffic_ops
      to.testlab.invalid:
        cdn: ALL
        component: traffic_opsdb
verifier:
  name: testinfra
  lint:
    name: flake8
